@startuml
title Register an Airport - POST /airport/registerAirport

actor User as "BackOffice Operator"

participant Controller  as "AirportController"
participant UseCase     as "<<@UseCase>>\nRegisterAirportUseCase"
participant Factory     as "AirportFactory"
participant Airport     as "Airport\nAggregate"
participant Repo        as "AirportRepository"

'----------'----------'----------'
'Connections

User -> Controller : POST /airport/registerAirport
activate Controller

Controller -> UseCase :
activate UseCase

UseCase -> Factory :
activate Factory

Factory -> Airport : createAirport()
activate Airport
Airport -> Factory :
deactivate Airport

Factory -> UseCase :
deactivate Factory

UseCase -> Repo : save

UseCase -> Controller :
deactivate UseCase

Controller -> User : HTTP 201 Created (JSON Response)
deactivate Controller

@enduml