spring.application.name=psoft_aisafe
security.jwt.secret=A83B47F2D5E8C91A64B73E9FA21C4D6E8B5F2A7C39E1D4B6F8A2C5E7D3B9F1A4
security.jwt.expiration-ms=86400000

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:aisafedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.show-sql=true