@startuml
autonumber
skinparam packageStyle rectangle

actor "ATCC Operator" as ATCC
participant "AircraftController" as Controller
participant "GetFleetStatusUseCase" as UseCase
participant "AircraftRepository" as Repo
participant "FleetStatusResponse" as ResponseDTO

ATCC -> Controller: GET /api/aircrafts/fleet-status
activate Controller

Controller -> UseCase: execute()
activate UseCase

UseCase -> Repo: findAll()
activate Repo
Repo --> UseCase: List<Aircraft> allAircrafts
deactivate Repo

note right of UseCase: 1. Streams groupingBy count()\n2. Streams map to details

UseCase -> ResponseDTO**: create(counts, details)
activate ResponseDTO
ResponseDTO --> UseCase: fleetStatusResponse
deactivate ResponseDTO

UseCase --> Controller: fleetStatusResponse
deactivate UseCase

Controller --> ATCC: 200 OK (JSON Payload)
deactivate Controller

@enduml