@startuml
autonumber
actor "ATCC" as ATCC
participant ":System" as System

activate ATCC
ATCC -> System : getRouteHistory(routeId)
activate System

note right of System: The system finds the route\nand returns all its versions\nordered from most recent to oldest.

System --> ATCC : informs operation success and returns list of route versions
deactivate System
deactivate ATCC
@enduml
