@startuml
autonumber
actor "Backoffice Operator" as BO
participant ":System" as System

activate BO
BO -> System : registerAircraftModel(manufacturer, modelName, fuelCapacity,\n maximumRange, cruisingSpeed, technicalDiagramUrl)
activate System

note right of System: The system validates the input,\nhandles the optional diagram URL,\nand registers the new model.

System --> BO : informs operation success and returns created model
deactivate System
deactivate BO
@enduml